---
# tasks file for database
- name: install mysql 
  ansible.builtin.yum:
    name: mysql-server
    state: present

- name: ensure mysql is started and enabled
  ansible.builtin.service:
     name: mysqld
     state: started 
     enabled: yes

- name: create /var/lib/mysql/mysql.sock
  ansible.builtin.file:
    path: /var/lib/mysql/mysql.sock
    state: touch

- name: create database
  community.mysql.mysql_db:
    name: homestead
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: create user
  community.mysql.mysql_user:
    name: homestead
    host: '0.0.0.0'
    password: sePret^i
    priv: '*.*:ALL,GRANT'
    state: present

